### ISSUE TITLE
time and battery icon hide under rounded corner

### ISSUE THREAD

**Issue by Spajderix** [crdroidandroid/android_device_motorola_ocean#1]
The phone has rounded corners on screen, and battery icon partialy hides away, as if the screen had straight corners

**Comment by gwolf2u** [comment]
tweak values from crDroid Settings - User Interface - Rounded corners

**Comment by Spajderix** [comment]
Tried all that, but while it makes corners even more round, it does not move the battery icon to be fully visible.

**Comment by neobuddy89** [comment]
yes, known issues.

**Comment by neobuddy89** [comment]
This issue is fixed.
https://github.com/crdroidandroid/android_frameworks_base/commit/421da76336037c721694777311f9941f321c5a5f
